import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "./utils/cn";
import { publicSans } from "./constant/font";
import { Navbar } from "./components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(publicSans, "indeterminate h-screen bg-white")}>
        <div className="mx-auto container pt-10">
        <Navbar />
        </div>
        {children}
      </body>
    </html>
  );
}
